insert into genre ("name") values('Поп');
insert into genre ("name") values('Рок');
insert into genre ("name") values('Рэп');
insert into genre ("name") values('Rock ''n'' Roll');
insert into genre ("name") values('Джаз');

insert into artist ("name") values('Michael Jackson');
insert into artist ("name") values('Madonna');
insert into artist ("name") values('Niletto');
insert into artist ("name") values('Виктор Цой');
insert into artist ("name") values('Юлия Чичерина');
insert into artist ("name") values('Elvis Presley');
insert into artist ("name") values('Paul McCartney');
insert into artist ("name") values('Louis Armstrong');
insert into artist ("name") values('Eminem');

insert into genreartist ("genre_id", "artist_id") values(1, 1);
insert into genreartist ("genre_id", "artist_id") values(1, 2);
insert into genreartist ("genre_id", "artist_id") values(1, 3);
insert into genreartist ("genre_id", "artist_id") values(3, 4);
insert into genreartist ("genre_id", "artist_id") values(3, 5);
insert into genreartist ("genre_id", "artist_id") values(4, 17);
insert into genreartist ("genre_id", "artist_id") values(5, 6);
insert into genreartist ("genre_id", "artist_id") values(5, 7);
insert into genreartist ("genre_id", "artist_id") values(6, 8);

insert into album ("title", "year") values('Thriller', 1982);
insert into album ("title", "year") values('Superpop', 2009);
insert into album ("title", "year") values('Ляля...', 2018);
insert into album ("title", "year") values('Печаль', 2000);
insert into album ("title", "year") values('Сказка о странствии и поиске счастья', 2015);
insert into album ("title", "year") values('Recovery', 2010);
insert into album ("title", "year") values('Love Songs', 2011);
insert into album ("title", "year") values('McCartney III', 2020);
insert into album ("title", "year") values('Singin'' Satchmo', 2019);

insert into artistalbum ("artist_id" , "album_id") values(1, 1);
insert into artistalbum ("artist_id" , "album_id") values(2, 2);
insert into artistalbum ("artist_id" , "album_id") values(3, 3);
insert into artistalbum ("artist_id" , "album_id") values(4, 4);
insert into artistalbum ("artist_id" , "album_id") values(5, 5);
insert into artistalbum ("artist_id" , "album_id") values(6, 7);
insert into artistalbum ("artist_id" , "album_id") values(7, 8);
insert into artistalbum ("artist_id" , "album_id") values(8, 9);
insert into artistalbum ("artist_id" , "album_id") values(17, 6);

insert into song (album_id, title, duration) values(1, 'Thriller', (5*60)+57);
insert into song (album_id, title, duration) values(1, 'Beat it', (4*60)+18);
insert into song (album_id, title, duration) values(2, 'Britney Spears feat. Madonna - Me Against The Music', (60*3)+44);
insert into song (album_id, title, duration) values(2, 'Hey You', (60*4)+16);
insert into song (album_id, title, duration) values(3, 'Сердце Танцует', (60*3)+4);
insert into song (album_id, title, duration) values(3, 'Ляля', (60*3)+10);
insert into song (album_id, title, duration) values(4, 'Группа крови (Remix)', (60*5)+6);
insert into song (album_id, title, duration) values(4, 'Мама мы все тяжело больны (Remix)', (60*3)+3);
insert into song (album_id, title, duration) values(5, 'Осколки', (60*3)+26);
insert into song (album_id, title, duration) values(5, 'Песня пути', (60*3)+48);
insert into song (album_id, title, duration) values(6, 'Not afraid', (60*4)+8);
insert into song (album_id, title, duration) values(6, 'Im On Fire', (60*3)+33);
insert into song (album_id, title, duration) values(7, 'Any Way You Want Me (That''s How It Will Be)', (60*2)+18);
insert into song (album_id, title, duration) values(7, 'Love Me', (60*2)+47);
insert into song (album_id, title, duration) values(8, 'Find My Way', (60*3)+55);
insert into song (album_id, title, duration) values(8, 'Deep Down', (60*5)+54);
insert into song (album_id, title, duration) values(9, 'I Only Have Eyes For You', (60*4)+13);
insert into song (album_id, title, duration) values(9, 'April In Portugal', (60*2)+42);

insert into collections ("name", "year") values ('Collection 1', 2015);
insert into collections ("name", "year") values ('Collection 2', 2016);
insert into collections ("name", "year") values ('Collection 3', 2017);
insert into collections ("name", "year") values ('Collection 4', 2018);
insert into collections ("name", "year") values ('Collection 5', 2019);
insert into collections ("name", "year") values ('Collection 6', 2020);
insert into collections ("name", "year") values ('Collection 7', 2021);
insert into collections ("name", "year") values ('Collection 8', 2022);

insert into collectionstrack (collections_id, song_id) values (1, 2);
insert into collectionstrack (collections_id, song_id) values (1, 3);
insert into collectionstrack (collections_id, song_id) values (1, 4);
insert into collectionstrack (collections_id, song_id) values (1, 5);
insert into collectionstrack (collections_id, song_id) values (2, 8);
insert into collectionstrack (collections_id, song_id) values (2, 9);
insert into collectionstrack (collections_id, song_id) values (2, 10);
insert into collectionstrack (collections_id, song_id) values (2, 11);
insert into collectionstrack (collections_id, song_id) values (3, 12);
insert into collectionstrack (collections_id, song_id) values (3, 13);
insert into collectionstrack (collections_id, song_id) values (4, 14);
insert into collectionstrack (collections_id, song_id) values (4, 15);
insert into collectionstrack (collections_id, song_id) values (4, 16);
insert into collectionstrack (collections_id, song_id) values (4, 17);
insert into collectionstrack (collections_id, song_id) values (5, 4);
insert into collectionstrack (collections_id, song_id) values (5, 5);
insert into collectionstrack (collections_id, song_id) values (5, 6);
insert into collectionstrack (collections_id, song_id) values (5, 7);
insert into collectionstrack (collections_id, song_id) values (6, 18);
insert into collectionstrack (collections_id, song_id) values (6, 19);
insert into collectionstrack (collections_id, song_id) values (7, 6);
insert into collectionstrack (collections_id, song_id) values (7, 7);
insert into collectionstrack (collections_id, song_id) values (7, 8);
insert into collectionstrack (collections_id, song_id) values (7, 9);
insert into collectionstrack (collections_id, song_id) values (7, 10);
insert into collectionstrack (collections_id, song_id) values (7, 11);
insert into collectionstrack (collections_id, song_id) values (8, 2);
insert into collectionstrack (collections_id, song_id) values (8, 3);
insert into collectionstrack (collections_id, song_id) values (8, 4);
insert into collectionstrack (collections_id, song_id) values (8, 5);
insert into collectionstrack (collections_id, song_id) values (8, 14);
insert into collectionstrack (collections_id, song_id) values (8, 15);
insert into collectionstrack (collections_id, song_id) values (8, 16);
insert into collectionstrack (collections_id, song_id) values (8, 17);


